package com.topica.tea.domain.enumeration;

/**
 * The EventStatus enumeration.
 */
public enum EventStatus {
    NEW,PROCESS,EDITOR,DIRECTOR_APPROVE,WAIT_DIRECTOR_APPROVE
    ,DIRECTOR_DENY,MANAGER_APPROVE,MANAGER_DENY,COORDINATE,INVALID,COMPLETED,WAIT_BOSS_APPROVE
    ,WAIT_SEND_BOSS
    ,PUBLISHED
    ,CANCEL
    ,NOT_YET_ORDER
}
