version: '2'
services:
    topicaeventamplify-app:
        image: topicaeventamplify
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://topicaeventamplify-mysql:3306/topicaeventamplify?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    topicaeventamplify-mysql:
        extends:
            file: mysql.yml
            service: topicaeventamplify-mysql
